name: Main Pipeline
on: 
 push:
  branches:
  - "main"

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 19
    - name: "Lanzar Test unitarios"
      run: |
        set -ev 
        cd modern-web-app
        npm ci
        npm run test:unit

  Build:
    runs-on: ubuntu-latest
    needs: Unittest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lanzar Build
        run: |
          set -ev
          cd modern-web-app
          npm ci
          npm run build

      
